name: lint

on: push

jobs: 
  super-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v6.4.1
        env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
